import { IdiomCategory } from '../types';

export const IDIOMS_CATEGORIES: IdiomCategory[] = [
  {
    category: 'General Usage',
    idioms: [
      { idiom: 'A dime a dozen', meaning: 'Very common and of little value.', example: 'Experts in this field are a dime a dozen.' },
      { idiom: 'Add insult to injury', meaning: 'To worsen an unfavorable situation.', example: 'To add insult to injury, after cancelling my flight, the airline refused to refund my ticket.' },
      { idiom: 'Beat around the bush', meaning: 'Avoid saying what you mean, usually because it is uncomfortable.', example: 'Stop beating around the bush and just tell me what happened.' },
      { idiom: 'Better late than never', meaning: 'Better to arrive or do something late than not at all.', example: 'He finally paid me the money he owed me. Well, better late than never.' },
      { idiom: 'Bite the bullet', meaning: 'To endure a difficult or unpleasant situation with courage.', example: 'I had to bite the bullet and finish the project even though I was tired.' },
      { idiom: 'Break the ice', meaning: 'To initiate social conversation or interaction.', example: 'He told a joke to break the ice at the start of the meeting.' },
      { idiom: 'Cost an arm and a leg', meaning: 'To be extremely expensive.', example: 'That new car must have cost him an arm and a leg.' },
      { idiom: 'Cut somebody some slack', meaning: 'Don\'t be so critical; be more forgiving.', example: 'He\'s having a tough week, so cut him some slack.' },
      { idiom: 'Don\'t judge a book by its cover', meaning: 'Don\'t judge something primarily on its appearance.', example: 'He may look a bit strange, but don\'t judge a book by its cover.' },
      { idiom: 'Get out of hand', meaning: 'To become uncontrollable.', example: 'The party got out of hand, and the police were called.' },
      { idiom: 'Get your act together', meaning: 'Behave properly or work more effectively.', example: 'You need to get your act together if you want to pass this class.' },
      { idiom: 'Go down in flames', meaning: 'To fail spectacularly.', example: 'His ambitious project went down in flames when he lost all funding.' },
      { idiom: 'Hang in there', meaning: 'Don\'t give up; persevere.', example: 'I know you\'re tired, but hang in there, you\'re almost finished.' },
      { idiom: 'Hit the nail on the head', meaning: 'To describe exactly what is causing a situation or problem.', example: 'You hit the nail on the head when you said our main issue is communication.' },
      { idiom: 'Jump on the bandwagon', meaning: 'Join a popular trend or activity.', example: 'So many people are buying that new phone; I might as well jump on the bandwagon.' },
      { idiom: 'Make a long story short', meaning: 'To tell something briefly.', example: 'To make a long story short, we missed our flight.' },
      { idiom: 'Miss the boat', meaning: 'To lose an opportunity.', example: 'The application was due yesterday; I think I missed the boat.' },
      { idiom: 'On the ball', meaning: 'To be quick to understand and react to things.', example: 'Our new project manager is really on the ball.' },
      { idiom: 'Pull yourself together', meaning: 'Calm down.', example: 'I know you\'re upset, but you need to pull yourself together and focus.' },
      { idiom: 'See eye to eye', meaning: 'To agree on a subject.', example: 'My boss and I don\'t always see eye to eye on marketing strategy.' },
      { idiom: 'So far so good', meaning: 'Progress has been satisfactory up to now.', example: 'How\'s the new project going? So far so good.' },
      { idiom: 'Speak of the devil', meaning: 'When the person you have just been talking about arrives.', example: 'Well, speak of the devil! We were just talking about you, Mark.' },
      { idiom: 'That\'s the last straw', meaning: 'The final tolerable act in a series of provocations.', example: 'He was late again, and that was the last straw. I fired him.' },
      { idiom: 'The best of both worlds', meaning: 'Enjoying two different opportunities at the same time.', example: 'Working from home is the best of both worlds; I have more family time and a great career.' },
      { idiom: 'Through thick and thin', meaning: 'Under all circumstances, no matter how difficult.', example: 'She has always supported me through thick and thin.' },
      { idiom: 'Your guess is as good as mine', meaning: 'I don\'t know either.', example: 'What time will he arrive? Your guess is as good as mine.' },
    ],
  },
  {
    category: 'Animals',
    idioms: [
      { idiom: 'A bull in a china shop', meaning: 'A clumsy person in a delicate situation.', example: 'He was like a bull in a china shop during the delicate negotiations.' },
      { idiom: 'A little bird told me', meaning: 'To have heard something from a secret source.', example: 'A little bird told me it\'s your birthday tomorrow.' },
      { idiom: 'Ants in your pants', meaning: 'To be unable to sit still.', example: 'The kids have ants in their pants today; they can\'t wait for the party.' },
      { idiom: 'Cat got your tongue?', meaning: 'A question asked when someone is unusually quiet.', example: 'You\'ve been silent all evening. Cat got your tongue?' },
      { idiom: 'Cry wolf', meaning: 'To raise a false alarm, with the result that a real alarm is ignored.', example: 'He has cried wolf so many times that no one believes him when he\'s actually in trouble.' },
      { idiom: 'Curiosity killed the cat', meaning: 'Being too inquisitive can lead to trouble.', example: 'I know you want to know what\'s in the box, but remember, curiosity killed the cat.' },
      { idiom: 'Fish out of water', meaning: 'To be in an unfamiliar and uncomfortable situation.', example: 'As a country boy, he felt like a fish out of water in the big city.' },
      { idiom: 'Go on a wild goose chase', meaning: 'To do something pointless or futile.', example: 'I went on a wild goose chase trying to find that rare book.' },
      { idiom: 'Hold your horses', meaning: 'To wait a moment; to not be so impatient.', example: 'Hold your horses! We\'re not ready to leave yet.' },
      { idiom: 'Kill two birds with one stone', meaning: 'To achieve two aims at once.', example: 'I can kill two birds with one stone by listening to an English podcast while I exercise.' },
      { idiom: 'Let sleeping dogs lie', meaning: 'To avoid restarting a conflict.', example: 'I wanted to ask him about the argument, but I decided to let sleeping dogs lie.' },
      { idiom: 'Let the cat out of the bag', meaning: 'To accidentally reveal a secret.', example: 'He let the cat out of the bag about the surprise party.' },
      { idiom: 'The elephant in the room', meaning: 'A major problem or controversial issue that is obviously present but avoided as a subject for discussion.', example: 'His gambling problem was the elephant in the room at the family dinner.' },
      { idiom: 'The lion\'s share', meaning: 'The largest portion of something.', example: 'As the lead investor, he took the lion\'s share of the profits.' },
      { idiom: 'When pigs fly', meaning: 'Something that will never happen.', example: 'He\'ll clean his room when pigs fly.' },
    ],
  },
  {
    category: 'Body Parts',
    idioms: [
      { idiom: 'All ears', meaning: 'Fully listening; attentive.', example: 'Tell me about your trip, I\'m all ears.' },
      { idiom: 'Bite your tongue', meaning: 'To stop yourself from saying something you want to say.', example: 'I had to bite my tongue to keep from criticizing his plan.' },
      { idiom: 'Break a leg', meaning: 'Good luck! (often said to actors before a performance).', example: 'You have a big performance tonight? Break a leg!' },
      { idiom: 'By the skin of your teeth', meaning: 'Just barely succeeding.', example: 'He passed the exam by the skin of his teeth.' },
      { idiom: '(Have a) foot in the door', meaning: 'A first step toward getting or doing something.', example: 'This internship could be my foot in the door at a great company.' },
      { idiom: 'Get cold feet', meaning: 'To become nervous about a big event and reconsider it.', example: 'The groom got cold feet the day before the wedding.' },
      { idiom: 'Get something off your chest', meaning: 'To talk about something that has been bothering you.', example: 'He felt much better after getting the problem off his chest.' },
      { idiom: 'Give someone the cold shoulder', meaning: 'To ignore someone deliberately.', example: 'After our argument, she gave me the cold shoulder for a week.' },
      { idiom: 'Have a change of heart', meaning: 'To change your opinion or the way you feel about something.', example: 'I was going to sell my car, but I had a change of heart.' },
      { idiom: 'Head over heels', meaning: 'Deeply in love.', example: 'They are head over heels for each other.' },
      { idiom: 'Keep an eye on', meaning: 'To watch or take care of something or someone.', example: 'Can you keep an eye on my bag for a minute?' },
      { idiom: 'Play it by ear', meaning: 'To decide how to deal with a situation as it develops.', example: 'We don\'t have a set schedule, we\'ll just play it by ear.' },
      { idiom: 'Pull someone\'s leg', meaning: 'To joke with someone; to tease them.', example: 'Don\'t worry, I\'m just pulling your leg. I didn\'t actually break your camera.' },
      { idiom: 'Rule of thumb', meaning: 'A broadly accurate guide or principle, based on practice rather than theory.', example: 'As a rule of thumb, you should add the pasta to boiling water.' },
    ],
  },
  {
    category: 'Feelings & Emotions',
    idioms: [
      { idiom: 'A blessing in disguise', meaning: 'A good thing that seemed bad at first.', example: 'Losing that job was a blessing in disguise; I found a much better one.' },
      { idiom: '(Have a) chip on your shoulder', meaning: 'To seem angry all the time because you think you have been treated unfairly.', example: 'He has a chip on his shoulder about not going to college.' },
      { idiom: 'Down in the dumps', meaning: 'Sad or depressed.', example: 'She\'s been down in the dumps ever since she lost her job.' },
      { idiom: 'Face the music', meaning: 'To accept responsibility for something you have done.', example: 'After crashing his dad\'s car, he had to go home and face the music.' },
      { idiom: 'Have mixed feelings', meaning: 'To be unsure how you feel about something.', example: 'I have mixed feelings about moving to a new city.' },
      { idiom: 'Head in the clouds', meaning: 'To be daydreaming and not paying attention.', example: 'He has his head in the clouds if he thinks he can pass the exam without studying.' },
      { idiom: 'Jump for joy', meaning: 'To be extremely happy.', example: 'She jumped for joy when she heard the good news.' },
      { idiom: 'On cloud nine', meaning: 'To be extremely happy and joyful.', example: 'She has been on cloud nine since she got engaged.' },
      { idiom: 'Saved by the bell', meaning: 'Rescued from a difficult situation at the very last moment.', example: 'I was about to give a wrong answer, but the fire alarm rang. I was saved by the bell!' },
      { idiom: 'Under the weather', meaning: 'To feel ill or sick.', example: 'I\'m feeling a bit under the weather today, so I\'m staying home.' },
    ],
  },
  {
    category: 'Food',
    idioms: [
      { idiom: 'A tough cookie', meaning: 'A very determined and resilient person.', example: 'She went through a lot, but she\'s a tough cookie.' },
      { idiom: '(The) apple of my eye', meaning: 'A person that is adored by someone.', example: 'His youngest daughter is the apple of his eye.' },
      { idiom: 'As cool as a cucumber', meaning: 'To be very calm, especially under pressure.', example: 'She was as cool as a cucumber during her job interview.' },
      { idiom: 'Bite off more than you can chew', meaning: 'To take on a task that is too big to handle.', example: 'By accepting two part-time jobs, he is biting off more than he can chew.' },
      { idiom: 'Cry over spilt milk', meaning: 'To be upset about something that has already happened and cannot be changed.', example: 'The report is already submitted; there\'s no use crying over spilt milk.' },
      { idiom: '(Don\'t) put all your eggs in one basket', meaning: 'Don\'t risk everything on the success of one venture.', example: 'It\'s wise to diversify your investments and not put all your eggs in one basket.' },
      { idiom: 'Go bananas', meaning: 'To become extremely angry, excited, or silly.', example: 'The crowd went bananas when the band came on stage.' },
      { idiom: 'In a nutshell', meaning: 'In a few words; concisely.', example: 'In a nutshell, the plan failed.' },
      { idiom: 'Piece of cake', meaning: 'Something that is very easy to do.', example: 'The exam was a piece of cake.' },
      { idiom: 'Sell like hotcakes', meaning: 'To sell very quickly and in large quantities.', example: 'The new phone is selling like hotcakes.' },
      { idiom: 'Spill the beans', meaning: 'To disclose a secret.', example: 'Come on, spill the beans! What did he say?' },
      { idiom: 'Take with a grain of salt', meaning: 'To not take something too seriously or literally.', example: 'You should take his promises with a grain of salt.' },
      { idiom: 'The cream of the crop', meaning: 'The best of a particular group.', example: 'The company only hires the cream of the crop from the top universities.' },
    ],
  },
  {
    category: 'Money',
    idioms: [
      { idiom: 'A penny for your thoughts', meaning: 'A way of asking what someone is thinking.', example: 'You seem quiet. A penny for your thoughts?' },
      { idiom: 'Break the bank', meaning: 'To be very expensive.', example: 'Eating at that restaurant will break the bank.' },
      { idiom: 'Cash cow', meaning: 'A business or product that generates a steady return of profits.', example: 'Their original software is a real cash cow for the company.' },
      { idiom: 'Go Dutch', meaning: 'To share the cost of something, especially a meal.', example: 'We decided to go Dutch on the dinner, so everyone paid for their own food.' },
      { idiom: 'Golden handshake', meaning: 'A large payment made to someone when they leave their job, either on retirement or when forced out.', example: 'The CEO received a generous golden handshake when he left the company.' },
      { idiom: 'Money doesn\'t grow on trees', meaning: 'Money is a limited resource and should be used carefully.', example: 'My son wants a new bike, but I told him that money doesn\'t grow on trees.' },
      { idiom: 'Money talks', meaning: 'People with money have more power and influence.', example: 'He got the best table in the restaurant. It\'s true that money talks.' },
      { idiom: 'Put your money where your mouth is', meaning: 'To take action to support what you are saying.', example: 'If you think the company will succeed, you should invest. Put your money where your mouth is.' },
    ]
  },
  {
    category: 'Time',
    idioms: [
      { idiom: 'Against the clock', meaning: 'To be rushed and have very little time to do something.', example: 'We were working against the clock to finish the report by the deadline.' },
      { idiom: 'At the eleventh hour', meaning: 'At the last possible moment.', example: 'They reached an agreement at the eleventh hour.' },
      { idiom: 'Beat the clock', meaning: 'To finish something just before the deadline.', example: 'She managed to beat the clock and submit her application just in time.' },
      { idiom: 'Call it a night', meaning: 'To stop an activity for the rest of the night.', example: 'It\'s getting late. I think I\'m going to call it a night.' },
      { idiom: 'In the nick of time', meaning: 'At the last possible moment.', example: 'The ambulance arrived in the nick of time to save him.' },
      { idiom: 'Kill time', meaning: 'To do something to occupy yourself while waiting for something to happen.', example: 'We have an hour before our flight, so let\'s go to the cafe to kill time.' },
      { idiom: 'Once in a blue moon', meaning: 'To happen very rarely.', example: 'I only see my old school friends once in a blue moon.' },
      { idiom: 'Turn back the hands of time', meaning: 'To go back to the past.', example: 'If I could turn back the hands of time, I would do things differently.' },
    ],
  },
  {
    category: 'Weather',
    idioms: [
      { idiom: 'A storm in a teacup', meaning: 'A lot of unnecessary anger and worry about a matter that is not important.', example: 'Their argument was just a storm in a teacup; they\'re friends again now.' },
      { idiom: 'Come rain or shine', meaning: 'No matter what happens.', example: 'I\'ll be at your game tomorrow, come rain or shine.' },
      { idiom: 'Every cloud has a silver lining', meaning: 'Every difficult or sad situation has a comforting or more hopeful aspect.', example: 'I was sad to leave my old job, but the new one is much better. Every cloud has a silver lining.' },
      { idiom: 'Get wind of something', meaning: 'To hear a rumor about something.', example: 'The reporter got wind of the scandal and published a story.' },
      { idiom: 'It never rains but it pours', meaning: 'When troubles come, they come all at once.', example: 'First I lost my keys, then my car broke down. It never rains but it pours.' },
      { idiom: 'On thin ice', meaning: 'In a precarious or risky situation.', example: 'After being late for the third time, he was on thin ice with his boss.' },
      { idiom: 'Rain on someone\'s parade', meaning: 'To spoil someone\'s pleasure or plans.', example: 'I don\'t want to rain on your parade, but the concert might be cancelled.' },
      { idiom: 'Steal someone\'s thunder', meaning: 'To take attention or credit away from someone else\'s achievements.', example: 'I was about to announce my engagement, but my sister stole my thunder by announcing her pregnancy.' },
    ]
  },
  {
    category: 'Work & Business',
    idioms: [
      { idiom: 'A learning curve', meaning: 'The rate of a person\'s progress in gaining experience or new skills.', example: 'There\'s a steep learning curve with this new software.' },
      { idiom: 'Back to the drawing board', meaning: 'When an attempt fails and it\'s time to start all over.', example: 'Our proposal was rejected, so it\'s back to the drawing board.' },
      { idiom: 'By the book', meaning: 'Strictly according to the rules.', example: 'Our accountant does everything by the book.' },
      { idiom: 'Call it a day', meaning: 'To stop working for the day.', example: 'We\'ve done enough for today, let\'s call it a day.' },
      { idiom: 'Cut corners', meaning: 'To do something in the easiest, cheapest, or fastest way, often sacrificing quality.', example: 'The company went out of business because they were cutting corners on safety.' },
      { idiom: 'Cut to the chase', meaning: 'Get to the point without wasting time.', example: 'I don\'t have much time, so please cut to the chase.' },
      { idiom: 'Go the extra mile', meaning: 'To make a special effort to achieve something.', example: 'She always goes the extra mile to help her clients.' },
      { idiom: 'Hit the ground running', meaning: 'To start something and proceed at a fast pace with great enthusiasm.', example: 'The new employee hit the ground running and was productive from her first day.' },
      { idiom: 'Learn the ropes', meaning: 'To learn the basics of a job or task.', example: 'It took me a few weeks to learn the ropes at my new job.' },
      { idiom: 'On the same page', meaning: 'To be in agreement about something.', example: 'Before we present to the client, let\'s make sure we are all on the same page.' },
      { idiom: 'Raise the bar', meaning: 'To set a higher standard.', example: 'Her performance really raised the bar for the rest of the team.' },
      { idiom: 'Think outside the box', meaning: 'To think in a creative and unconventional way.', example: 'We need to think outside the box to solve this problem.' },
    ],
  },
];