import { PhrasalVerbCategory } from '../types';

export const PHRASAL_VERBS_CATEGORIES: PhrasalVerbCategory[] = [
  {
    category: 'Communication',
    verbs: [
      { phrasalVerb: 'bring up', meaning: 'Start talking about a particular subject.', example: 'She was afraid to bring up the subject of money.' },
      { phrasalVerb: 'call back', meaning: 'Return a phone call.', example: 'I\'ll call you back as soon as I\'m free.' },
      { phrasalVerb: 'catch up', meaning: 'Exchange news with someone.', example: 'Let\'s catch up over coffee next week.' },
      { phrasalVerb: 'chime in', meaning: 'Join a conversation; interrupt with a comment.', example: 'He chimed in with his own opinion.' },
      { phrasalVerb: 'get across', meaning: 'Successfully communicate an idea.', example: 'He found it difficult to get his point across to the committee.' },
      { phrasalVerb: 'get through to', meaning: 'Make someone understand something.', example: 'I just can\'t get through to him that he needs to study.' },
      { phrasalVerb: 'hang up', meaning: 'End a phone call.', example: 'Don\'t hang up on me, we need to talk.' },
      { phrasalVerb: 'put forward', meaning: 'Propose an idea for consideration.', example: 'She put forward a new idea for the marketing campaign.' },
      { phrasalVerb: 'spell out', meaning: 'Explain something very clearly.', example: 'The teacher had to spell out the instructions for the new student.' },
      { phrasalVerb: 'talk over', meaning: 'Discuss a problem or situation.', example: 'We need to talk over our plans for the weekend.' },
    ],
  },
  {
    category: 'Success & Failure',
    verbs: [
      { phrasalVerb: 'carry out', meaning: 'Complete a plan or task.', example: 'The team successfully carried out the experiment.' },
      { phrasalVerb: 'fall through', meaning: 'Fail to happen.', example: 'Our travel plans fell through at the last minute.' },
      { phrasalVerb: 'follow through', meaning: 'Continue an action or task to its conclusion.', example: 'He made a promise but didn\'t follow through.' },
      { phrasalVerb: 'give up', meaning: 'Stop trying to do something.', example: 'He gave up trying to fix the old computer.' },
      { phrasalVerb: 'mess up', meaning: 'Make a mistake or do something badly.', example: 'I really messed up the exam.' },
      { phrasalVerb: 'pan out', meaning: '(of a plan or situation) develop in a particular way.', example: 'We\'ll have to see how his new business venture pans out.' },
      { phrasalVerb: 'pull off', meaning: 'Succeed in doing something difficult.', example: 'I can\'t believe they pulled off the deal.' },
      { phrasalVerb: 'scrape through', meaning: 'Succeed in something but with a lot of difficulty.', example: 'He only just scraped through his final exams.' },
    ],
  },
    {
    category: 'Feelings & Emotions',
    verbs: [
      { phrasalVerb: 'break down', meaning: 'Lose control of your emotions and start crying.', example: 'She broke down in tears when she heard the news.' },
      { phrasalVerb: 'calm down', meaning: 'Become less angry, upset, or excited.', example: 'You need to calm down and tell me what happened.' },
      { phrasalVerb: 'cheer up', meaning: 'Become happier or make someone happier.', example: 'I bought her some flowers to cheer her up.' },
      { phrasalVerb: 'freak out', meaning: 'To become very anxious, upset, or afraid.', example: 'He freaked out when he saw the spider.' },
      { phrasalVerb: 'lighten up', meaning: 'Become less serious.', example: 'Oh, lighten up! It was just a joke.' },
      { phrasalVerb: 'look forward to', meaning: 'Feel excited about something that is going to happen.', example: 'I\'m really looking forward to my vacation.' },
      { phrasalVerb: 'open up', meaning: 'To start to talk more about yourself and your feelings.', example: 'He finds it hard to open up about his problems.' },
    ],
  },
  {
    category: 'Work: Jobs & Career',
    verbs: [
      { phrasalVerb: 'burn out', meaning: 'Become exhausted from overworking.', example: 'If you keep working 12-hour days, you\'ll burn out.' },
      { phrasalVerb: 'fill in for', meaning: 'Do someone\'s job for them while they are away.', example: 'Can you fill in for me while I\'m on lunch break?' },
      { phrasalVerb: 'get ahead', meaning: 'To be successful in the work that you do.', example: 'She works hard to get ahead in her career.' },
      { phrasalVerb: 'knuckle down', meaning: 'Start working hard, especially when you should have done it earlier.', example: 'It\'s time to knuckle down and study for the exams.' },
      { phrasalVerb: 'lay off', meaning: 'End someone\'s employment due to business reasons.', example: 'The company had to lay off 50 workers.' },
      { phrasalVerb: 'slack off', meaning: 'To work less hard or with less energy than you should.', example: 'He was fired for slacking off at work.' },
      { phrasalVerb: 'step down', meaning: 'Resign from a position.', example: 'The CEO decided to step down after 10 years.' },
      { phrasalVerb: 'take on', meaning: 'Accept new work or responsibility.', example: 'She decided to take on the role of project manager.' },
      { phrasalVerb: 'take over', meaning: 'Take control of a company or role.', example: 'He will take over as manager when Sarah leaves.' },
    ],
  },
  {
    category: 'Money & Business',
    verbs: [
      { phrasalVerb: 'bail out', meaning: 'Rescue a company from financial difficulties.', example: 'The government had to bail out the failing bank.' },
      { phrasalVerb: 'buy up', meaning: 'Buy large quantities of something.', example: 'Investors are buying up property in the city center.' },
      { phrasalVerb: 'chip in', meaning: 'To contribute some money to a group effort.', example: 'We all chipped in to buy her a leaving present.' },
      { phrasalVerb: 'cut back on', meaning: 'Reduce spending.', example: 'We need to cut back on our expenses this month.' },
      { phrasalVerb: 'fork over/out', meaning: 'To pay an amount of money, especially unwillingly.', example: 'I had to fork over $100 for the speeding ticket.' },
      { phrasalVerb: 'pay off', meaning: 'Finish paying money that is owed.', example: 'It took them ten years to pay off their mortgage.' },
      { phrasalVerb: 'rip off', meaning: 'Charge someone too much money for something.', example: 'The tourist felt he had been ripped off by the taxi driver.' },
      { phrasalVerb: 'save up', meaning: 'Save money for a specific purpose.', example: 'I\'m saving up for a new car.' },
      { phrasalVerb: 'sell out', meaning: 'Sell all of the items.', example: 'The tickets for the concert sold out in minutes.' },
      { phrasalVerb: 'splash out', meaning: 'To spend a lot of money on something.', example: 'She splashed out on a new designer handbag.' },
    ],
  },
  {
    category: 'Relationships',
    verbs: [
      { phrasalVerb: 'ask out', meaning: 'To invite someone for a date.', example: 'He finally asked her out.' },
      { phrasalVerb: 'break up', meaning: 'End a romantic relationship.', example: 'She broke up with her boyfriend last week.' },
      { phrasalVerb: 'drift apart', meaning: 'Become less close to someone over time.', example: 'After college, we slowly drifted apart.' },
      { phrasalVerb: 'fall out', meaning: 'Have an argument and stop being friends.', example: 'They fell out over something trivial.' },
      { phrasalVerb: 'get along', meaning: 'Have a friendly relationship with someone.', example: 'I get along well with my colleagues.' },
      { phrasalVerb: 'grow apart', meaning: 'To stop having a close relationship with someone over time.', example: 'We were good friends, but we\'ve grown apart over the years.' },
      { phrasalVerb: 'hit it off', meaning: 'Immediately like each other.', example: 'We hit it off the first time we met.' },
      { phrasalVerb: 'look up to', meaning: 'Admire and respect someone.', example: 'He always looked up to his older brother.' },
      { phrasalVerb: 'make up', meaning: 'Forgive someone after an argument.', example: 'They had a fight, but they made up the next day.' },
      { phrasalVerb: 'settle down', meaning: 'To start living a quieter life, especially by getting married.', example: 'They decided to settle down and start a family.' },
    ],
  },
  {
    category: 'Health & Daily Routines',
    verbs: [
      { phrasalVerb: 'come down with', meaning: 'Start to get an illness.', example: 'I think I\'m coming down with a cold.' },
      { phrasalVerb: 'cut down on', meaning: 'Reduce the consumption of something.', example: 'I need to cut down on sugar.' },
      { phrasalVerb: 'doze off', meaning: 'To fall asleep, especially for a short time.', example: 'He dozed off during the boring lecture.' },
      { phrasalVerb: 'freshen up', meaning: 'To wash and make yourself look clean and neat.', example: 'I need to freshen up before the guests arrive.' },
      { phrasalVerb: 'get over', meaning: 'Recover from an illness.', example: 'It took him a long time to get over the flu.' },
      { phrasalVerb: 'lie down', meaning: 'Rest on your back.', example: 'I\'m going to lie down for a few minutes.' },
      { phrasalVerb: 'pass out', meaning: 'Faint or lose consciousness.', example: 'He passed out from the heat.' },
      { phrasalVerb: 'sleep in', meaning: 'To sleep later than usual.', example: 'I love to sleep in on Saturdays.' },
      { phrasalVerb: 'wake up', meaning: 'Stop sleeping.', example: 'I wake up at 7 AM every day.' },
      { phrasalVerb: 'work out', meaning: 'Exercise.', example: 'She works out at the gym three times a week.' },
    ],
  },
  {
    category: 'Travel & Movement',
    verbs: [
      { phrasalVerb: 'check in', meaning: 'Register at a hotel or airport.', example: 'We need to check in at least two hours before the flight.' },
      { phrasalVerb: 'check out', meaning: 'Leave and pay for your stay at a hotel.', example: 'We need to check out of the hotel by 11 AM.' },
      { phrasalVerb: 'drop off', meaning: 'Take someone or something to a place and leave them there.', example: 'Can you drop me off at the station?' },
      { phrasalVerb: 'get away', meaning: 'Go on vacation.', example: 'I need to get away for a few days to relax.' },
      { phrasalVerb: 'get off', meaning: 'To leave a bus, train, or plane.', example: 'We need to get off at the next stop.' },
      { phrasalVerb: 'get on', meaning: 'To board a bus, train, or plane.', example: 'He got on the bus at the wrong stop.' },
      { phrasalVerb: 'see off', meaning: 'Go to the airport or station to say goodbye to someone.', example: 'Her family came to see her off at the station.' },
      { phrasalVerb: 'set off', meaning: 'Start a journey.', example: 'We set off early in the morning to avoid traffic.' },
      { phrasalVerb: 'stop over', meaning: 'To stay somewhere for a short time during a long journey.', example: 'We stopped over in Dubai for a night on the way to Australia.' },
      { phrasalVerb: 'take off', meaning: 'When an airplane leaves the ground.', example: 'The plane took off on time.' },
    ],
  },
  {
    category: 'Actions & Movement',
    verbs: [
      { phrasalVerb: 'get up', meaning: 'To get out of bed.', example: 'What time do you usually get up?' },
      { phrasalVerb: 'go back', meaning: 'To return to a place.', example: 'I have to go back to the office to get my phone.' },
      { phrasalVerb: 'look around', meaning: 'Explore a place.', example: 'We had some time to look around the city.' },
      { phrasalVerb: 'run around', meaning: 'Be very busy doing many different things.', example: 'I\'ve been running around all day trying to get everything done.' },
      { phrasalVerb: 'show up', meaning: 'Arrive or appear somewhere.', example: 'He finally showed up an hour late.' },
      { phrasalVerb: 'sit down', meaning: 'Move into a sitting position.', example: 'Sit down and make yourself comfortable.' },
      { phrasalVerb: 'stand up', meaning: 'Rise to a standing position.', example: 'Please stand up when the judge enters.' },
      { phrasalVerb: 'turn around', meaning: 'To change direction and face the opposite way.', example: 'I forgot my wallet, so I had to turn around and go back home.' },
    ],
  },
  {
    category: 'Starting & Finishing',
    verbs: [
      { phrasalVerb: 'carry on', meaning: 'To continue doing something.', example: 'Please carry on with your work while I\'m away.' },
      { phrasalVerb: 'end up', meaning: 'Finally be in a particular place or situation.', example: 'We got lost and ended up on the wrong side of town.' },
      { phrasalVerb: 'get down to', meaning: 'To start doing something seriously.', example: 'It\'s time to get down to business.' },
      { phrasalVerb: 'give in', meaning: 'To stop resisting; to surrender.', example: 'The children kept asking for candy, and finally their mother gave in.' },
      { phrasalVerb: 'hold off', meaning: 'Delay doing something.', example: 'Let\'s hold off making a decision until we have more information.' },
      { phrasalVerb: 'kick off', meaning: 'Begin an event or meeting.', example: 'The festival will kick off with a parade.' },
      { phrasalVerb: 'run out of', meaning: 'Have no more of something left.', example: 'We\'ve run out of milk.' },
      { phrasalVerb: 'start over', meaning: 'To begin something again.', example: 'This isn\'t working, let\'s start over.' },
      { phrasalVerb: 'wrap up', meaning: 'Finish or complete something.', example: 'Let\'s wrap up this meeting by 5 PM.' },
    ],
  },
  {
    category: 'Solving Problems & Decisions',
    verbs: [
      { phrasalVerb: 'come up with', meaning: 'Think of a plan or idea.', example: 'He came up with a brilliant plan to save money.' },
      { phrasalVerb: 'deal with', meaning: 'Take action to solve a problem.', example: 'You need to deal with this issue immediately.' },
      { phrasalVerb: 'figure out', meaning: 'Understand or find the solution to a problem.', example: 'I can\'t figure out how to use this software.' },
      { phrasalVerb: 'get around', meaning: 'To find a way of dealing with or avoiding a problem.', example: 'There\'s no getting around the fact that you have to take the exam.' },
      { phrasalVerb: 'mull over', meaning: 'To think carefully about something over a period of time.', example: 'I need a few days to mull it over before I make a decision.' },
      { phrasalVerb: 'sleep on it', meaning: 'Delay making a decision until the next day.', example: 'I\'m not sure what to do; I\'ll have to sleep on it.' },
      { phrasalVerb: 'think over', meaning: 'Consider something carefully before making a decision.', example: 'I need some time to think over your offer.' },
      { phrasalVerb: 'weigh up', meaning: 'To consider the good and bad aspects of something before making a decision.', example: 'You should weigh up the pros and cons before accepting the job.' },
      { phrasalVerb: 'work out', meaning: 'Find a solution to a problem.', example: 'We need to work out a compromise.' },
    ],
  },
    {
    category: 'Food & Drink',
    verbs: [
      { phrasalVerb: 'cut up', meaning: 'Cut something into small pieces.', example: 'Could you cut up the vegetables for the salad?' },
      { phrasalVerb: 'dig in', meaning: 'To start eating eagerly.', example: 'The food is ready. Dig in!' },
      { phrasalVerb: 'drink up', meaning: 'Finish your drink.', example: 'Drink up, we have to leave in five minutes.' },
      { phrasalVerb: 'eat out', meaning: 'Eat at a restaurant instead of at home.', example: 'We\'re too tired to cook, let\'s eat out tonight.' },
      { phrasalVerb: 'polish off', meaning: 'To finish all of a particular dish or meal.', example: 'He polished off the entire pizza by himself.' },
      { phrasalVerb: 'whip up', meaning: 'Quickly make a meal or something to eat.', example: 'I can whip up a simple pasta dish for dinner.' },
    ],
  },
  {
    category: 'Technology & Computers',
    verbs: [
      { phrasalVerb: 'back up', meaning: 'Make a copy of computer data.', example: 'You should always back up your important files.' },
      { phrasalVerb: 'boot up', meaning: 'Start a computer.', example: 'My computer takes a long time to boot up.' },
      { phrasalVerb: 'go offline', meaning: 'To disconnect from the internet.', example: 'I\'m going offline for a few hours to focus on my work.' },
      { phrasalVerb: 'log in / on', meaning: 'Enter your username and password to start using a system.', example: 'I can\'t log in because I forgot my password.' },
      { phrasalVerb: 'log out / off', meaning: 'Sign out of a system.', example: 'Don\'t forget to log out when you finish.' },
      { phrasalVerb: 'print out', meaning: 'To produce a paper copy of a document from a computer.', example: 'Could you print out this report for me?' },
      { phrasalVerb: 'scroll down/up', meaning: 'To move information on a screen to see a different part of it.', example: 'Just scroll down to the bottom of the page.' },
      { phrasalVerb: 'shut down', meaning: 'Turn off a computer.', example: 'Please shut down your computer before you leave.' },
      { phrasalVerb: 'sign up', meaning: 'Create an account for a service.', example: 'You need to sign up to use the new features.' },
    ],
  },
    {
    category: 'Crime & Authority',
    verbs: [
      { phrasalVerb: 'break in / into', meaning: 'Enter a building illegally.', example: 'Someone tried to break into our house last night.' },
      { phrasalVerb: 'get away with', meaning: 'Avoid punishment for a crime.', example: 'He thought he could get away with cheating on the test.' },
      { phrasalVerb: 'hold up', meaning: 'Rob someone using violence or threats.', example: 'The gang held up a bank and stole thousands of dollars.' },
      { phrasalVerb: 'let off', meaning: 'Give someone a lighter punishment than they deserve.', example: 'The judge let him off with a warning.' },
      { phrasalVerb: 'own up', meaning: 'To admit that you have done something wrong.', example: 'No one owned up to breaking the window.' },
      { phrasalVerb: 'report to', meaning: 'To be accountable to someone at a higher level.', example: 'You will report directly to the manager.' },
      { phrasalVerb: 'track down', meaning: 'To find someone or something after a long search.', example: 'The police managed to track down the thief.' },
      { phrasalVerb: 'turn in', meaning: 'Give someone to the police.', example: 'He decided to turn himself in to the authorities.' },
    ],
  },
  {
    category: 'Academic Writing & Learning',
    verbs: [
        { phrasalVerb: 'bone up on', meaning: 'To study a subject intensively to prepare for something.', example: 'I need to bone up on my history before the exam.' },
        { phrasalVerb: 'brush up on', meaning: 'To improve your knowledge of something you have partly forgotten.', example: 'I should brush up on my Spanish before my trip to Madrid.' },
        { phrasalVerb: 'fall behind', meaning: 'Fail to keep up with schoolwork.', example: 'She was sick for a week and fell behind in her classes.' },
        { phrasalVerb: 'go over', meaning: 'Review or check something.', example: 'Let\'s go over the main points of the chapter.' },
        { phrasalVerb: 'hand in', meaning: 'Submit an assignment.', example: 'You must hand in your essay by Friday.' },
        { phrasalVerb: 'jot down', meaning: 'Write something quickly.', example: 'I should jot down his phone number before I forget it.' },
        { phrasalVerb: 'look up', meaning: 'Find information in a book or database.', example: 'If you don\'t know the word, look it up in a dictionary.' },
        { phrasalVerb: 'point out', meaning: 'To draw attention to a fact.', example: 'The author points out that the data is inconclusive.' },
        { phrasalVerb: 'read up on', meaning: 'To read a lot about a subject to become informed.', example: 'I need to read up on the company before my job interview.' },
        { phrasalVerb: 'sum up', meaning: 'Summarize the main points.', example: 'To sum up, the research shows a clear correlation.' },
    ],
  },
];
